const actions = {
  SET_LOADING: "SET_LOADING",
  SET_EVM_ADDRESS: "SET_EVM_ADDRESS",
  FILTER_ASSETS_BY_PLATFORM: "FILTER_ASSETS_BY_PLATFORM",
  OPEN_WALLET_MODAL: "OPEN_WALLET_MODAL",
  OPEN_ADD_CEX_MODAL: "OPEN_ADD_CEX_MODAL",
  SET_CEX_ASSETS: "SET_CEX_ASSETS",
  SET_DEX_ASSETS: "SET_DEX_ASSETS",
  SET_NET_WORTH: "SET_NET_WORTH",
  SET_ENS_NAME: "SET_ENS_NAME",
};

export default actions;
