export const ACTIONS = {
  SET_LOADING: "SET_LOADING",
  SET_EVM_ADDRESS: "SET_EVM_ADDRESS",
  ADD_NET_WORTH: "ADD_NET_WORTH",
  FILTER_ASSETS_BY_CHAIN: "FILTER_ASSETS_BY_CHAIN",
  OPEN_WALLET_MODAL: "OPEN_WALLET_MODAL",
  OPEN_ADD_CEX_MODAL: "OPEN_ADD_CEX_MODAL",
  SET_CEX_ASSETS: "SET_CEX_ASSETS",
};
