export const ACTIONS = {
  SET_EVM_ADDRESS: "SET_EVM_ADDRESS",
  FILTER_ASSETS_BY_CHAIN: "FILTER_ASSETS_BY_CHAIN",
  OPEN_WALLET_MODAL: "OPEN_WALLET_MODAL",
  OPEN_ADD_CEX_MODAL: "OPEN_ADD_CEX_MODAL",
};
